# Generated by Django 5.2.17 on 2026-10-02 11:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('signature_id', models.PositiveIntegerField()),
                ('signature', models.CharField(max_length=512)),
                ('classification', models.CharField(blank=True, max_length=128)),
                ('priority', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('protocol', models.CharField(blank=True, max_length=16)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('source_port', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)])),
                ('destination_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('destination_port', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)])),
                ('payload_available', models.BooleanField(default=False)),
                ('payload_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Must be a lowercase 64-character hex SHA-256.')])),
                ('payload_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('raw_event', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='sensors.sensor')),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
                'indexes': [models.Index(fields=['severity', '-timestamp'], name='alerts_aler_severit_0a17c6_idx'), models.Index(fields=['signature_id'], name='alerts_aler_signatu_872689_idx'), models.Index(fields=['sensor', '-timestamp'], name='alerts_aler_sensor__48fb0e_idx'), models.Index(fields=['protocol'], name='alerts_aler_protoco_26647b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('payload_available', False), ('payload_hash__isnull', False), _connector='OR'), name='alert_payload_requires_hash')],
            },
        ),
    ]
