# Generated by Django 5.2.17 on 2026-10-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('sensors', '0002_sensor_api_key_created_at_sensor_api_key_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='event_id',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(condition=models.Q(('event_id__isnull', False)), fields=('sensor', 'event_id'), name='alert_unique_event_per_sensor'),
        ),
    ]
