# Generated by Django 5.2.17 on 2026-10-02 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VirusTotalResult',
            fields=[
                ('sha256', models.CharField(max_length=64, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Must be a lowercase 64-character hex SHA-256.')])),
                ('outcome', models.CharField(choices=[('FOUND', 'Found'), ('NOT_FOUND', 'Not found'), ('ERROR', 'Error')], max_length=10)),
                ('malicious', models.PositiveIntegerField(blank=True, null=True)),
                ('suspicious', models.PositiveIntegerField(blank=True, null=True)),
                ('undetected', models.PositiveIntegerField(blank=True, null=True)),
                ('total', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('fetched_at', models.DateTimeField()),
            ],
        ),
    ]
