# Generated by Django 5.2.17 on 2026-10-02 11:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('sha256', models.CharField(max_length=64, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Must be a lowercase 64-character hex SHA-256.')])),
                ('first_seen', models.DateTimeField(db_index=True)),
                ('last_seen', models.DateTimeField()),
                ('size', models.PositiveBigIntegerField()),
                ('mime_type', models.CharField(blank=True, max_length=255)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('signature_id', models.PositiveIntegerField(blank=True, null=True)),
                ('signature', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('CLEAN', 'Clean'), ('SUSPICIOUS', 'Suspicious'), ('MALICIOUS', 'Malicious'), ('ERROR', 'Error')], db_index=True, default='UNKNOWN', max_length=12)),
                ('vt_malicious', models.PositiveIntegerField(blank=True, null=True)),
                ('vt_suspicious', models.PositiveIntegerField(blank=True, null=True)),
                ('vt_undetected', models.PositiveIntegerField(blank=True, null=True)),
                ('vt_total', models.PositiveIntegerField(blank=True, null=True)),
                ('vt_last_checked', models.DateTimeField(blank=True, null=True)),
                ('vt_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payloads', to='sensors.sensor')),
            ],
            options={
                'ordering': ['-first_seen'],
            },
        ),
    ]
