# Generated by Django 5.2.17 on 2026-10-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('os', models.CharField(choices=[('LINUX', 'Linux'), ('WINDOWS', 'Windows')], max_length=10)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('snort_version', models.CharField(blank=True, max_length=32)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
