# Generated by Django 5.2.17 on 2026-10-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='api_key_created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='api_key_hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='sensor',
            name='api_key_prefix',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='collector_version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='sensor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
